$env:MEM0_USER_ID = "mauls"
$env:MEM0_PROVIDER = "ollama"
$env:MEM0_LLM_MODEL = "qwen2.5:1.5b"
$env:MEM0_ENABLE_GRAPH = "false"
$env:MEM0_QDRANT_URL = "http://localhost:6333"
$env:MEM0_OLLAMA_BASE_URL = "http://localhost:11434"
$env:MEM0_EMBEDDING_MODEL = "bge-m3:latest"
$env:MEM0_TRANSPORT = "stdio"
& "C:\Users\mauls\.local\bin\mem0-mcp-selfhosted.exe"